//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIGWebServiceReference
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ns.verticalscreen.com/", ConfigurationName="BIGWebServiceReference.TokioMarineWebServiceSoapV2")]
    public interface TokioMarineWebServiceSoapV2
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ns.verticalscreen.com/Submit", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<BIGWebServiceReference.SubmitResponseSubmitResult> SubmitAsync(BIGWebServiceReference.SubmitRequest Request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ns.verticalscreen.com/")]
    public partial class SubmitRequest
    {
        
        private SubmitRequestREQUEST_INFO[] rEQUEST_INFOField;
        
        private SubmitRequestSUBJECT_INFO[] sUBJECT_INFOField;
        
        private SubmitRequestSERVICES[] sERVICESField;
        
        private SubmitRequestCUSTOMTYPE[][] cUSTOMField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("REQUEST_INFO", Order=0)]
        public SubmitRequestREQUEST_INFO[] REQUEST_INFO
        {
            get
            {
                return this.rEQUEST_INFOField;
            }
            set
            {
                this.rEQUEST_INFOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SUBJECT_INFO", Order=1)]
        public SubmitRequestSUBJECT_INFO[] SUBJECT_INFO
        {
            get
            {
                return this.sUBJECT_INFOField;
            }
            set
            {
                this.sUBJECT_INFOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SERVICES", Order=2)]
        public SubmitRequestSERVICES[] SERVICES
        {
            get
            {
                return this.sERVICESField;
            }
            set
            {
                this.sERVICESField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("TYPE", typeof(SubmitRequestCUSTOMTYPE), IsNullable=false)]
        public SubmitRequestCUSTOMTYPE[][] CUSTOM
        {
            get
            {
                return this.cUSTOMField;
            }
            set
            {
                this.cUSTOMField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ns.verticalscreen.com/")]
    public partial class SubmitRequestREQUEST_INFO
    {
        
        private string userNmField;
        
        private string userPwdField;
        
        private string requestIdField;
        
        private string requesterField;
        
        private string clientNumField;
        
        private string clientPackageField;
        
        private string dupOverrideCdField;
        
        private string clientBillingCdField;
        
        private string subjectWantsCopyIndField;
        
        private string commentsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string UserNm
        {
            get
            {
                return this.userNmField;
            }
            set
            {
                this.userNmField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string UserPwd
        {
            get
            {
                return this.userPwdField;
            }
            set
            {
                this.userPwdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string RequestId
        {
            get
            {
                return this.requestIdField;
            }
            set
            {
                this.requestIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Requester
        {
            get
            {
                return this.requesterField;
            }
            set
            {
                this.requesterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ClientNum
        {
            get
            {
                return this.clientNumField;
            }
            set
            {
                this.clientNumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string ClientPackage
        {
            get
            {
                return this.clientPackageField;
            }
            set
            {
                this.clientPackageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string DupOverrideCd
        {
            get
            {
                return this.dupOverrideCdField;
            }
            set
            {
                this.dupOverrideCdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string ClientBillingCd
        {
            get
            {
                return this.clientBillingCdField;
            }
            set
            {
                this.clientBillingCdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string SubjectWantsCopyInd
        {
            get
            {
                return this.subjectWantsCopyIndField;
            }
            set
            {
                this.subjectWantsCopyIndField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Comments
        {
            get
            {
                return this.commentsField;
            }
            set
            {
                this.commentsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ns.verticalscreen.com/")]
    public partial class SubmitRequestSUBJECT_INFO
    {
        
        private SubmitRequestSUBJECT_INFONAME[] nAMEField;
        
        private SubmitRequestSUBJECT_INFOADDRESS[] aDDRESSField;
        
        private SubmitRequestSUBJECT_INFOPHONE[] pHONEField;
        
        private string emailAddressField;
        
        private string sSNTaxIdNumField;
        
        private string sSNCountryNameField;
        
        private string birthDtField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NAME", Order=0)]
        public SubmitRequestSUBJECT_INFONAME[] NAME
        {
            get
            {
                return this.nAMEField;
            }
            set
            {
                this.nAMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ADDRESS", Order=1)]
        public SubmitRequestSUBJECT_INFOADDRESS[] ADDRESS
        {
            get
            {
                return this.aDDRESSField;
            }
            set
            {
                this.aDDRESSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PHONE", Order=2)]
        public SubmitRequestSUBJECT_INFOPHONE[] PHONE
        {
            get
            {
                return this.pHONEField;
            }
            set
            {
                this.pHONEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string EmailAddress
        {
            get
            {
                return this.emailAddressField;
            }
            set
            {
                this.emailAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string SSNTaxIdNum
        {
            get
            {
                return this.sSNTaxIdNumField;
            }
            set
            {
                this.sSNTaxIdNumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string SSNCountryName
        {
            get
            {
                return this.sSNCountryNameField;
            }
            set
            {
                this.sSNCountryNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string BirthDt
        {
            get
            {
                return this.birthDtField;
            }
            set
            {
                this.birthDtField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ns.verticalscreen.com/")]
    public partial class SubmitRequestSUBJECT_INFONAME
    {
        
        private string firstNmField;
        
        private string middleNmField;
        
        private string lastNmField;
        
        private SubmitRequestSUBJECT_INFONAMEType typeField;
        
        private bool typeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string FirstNm
        {
            get
            {
                return this.firstNmField;
            }
            set
            {
                this.firstNmField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string MiddleNm
        {
            get
            {
                return this.middleNmField;
            }
            set
            {
                this.middleNmField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string LastNm
        {
            get
            {
                return this.lastNmField;
            }
            set
            {
                this.lastNmField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public SubmitRequestSUBJECT_INFONAMEType Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TypeSpecified
        {
            get
            {
                return this.typeFieldSpecified;
            }
            set
            {
                this.typeFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ns.verticalscreen.com/")]
    public enum SubmitRequestSUBJECT_INFONAMEType
    {
        
        /// <remarks/>
        Primary,
        
        /// <remarks/>
        AKA,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ns.verticalscreen.com/")]
    public partial class SubmitRequestSUBJECT_INFOADDRESS
    {
        
        private string address1Field;
        
        private string address2Field;
        
        private string cityNmField;
        
        private string stateCdField;
        
        private string zipCodeField;
        
        private string countryCdField;
        
        private SubmitRequestSUBJECT_INFOADDRESSType typeField;
        
        private bool typeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Address1
        {
            get
            {
                return this.address1Field;
            }
            set
            {
                this.address1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Address2
        {
            get
            {
                return this.address2Field;
            }
            set
            {
                this.address2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string CityNm
        {
            get
            {
                return this.cityNmField;
            }
            set
            {
                this.cityNmField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string StateCd
        {
            get
            {
                return this.stateCdField;
            }
            set
            {
                this.stateCdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ZipCode
        {
            get
            {
                return this.zipCodeField;
            }
            set
            {
                this.zipCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string CountryCd
        {
            get
            {
                return this.countryCdField;
            }
            set
            {
                this.countryCdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public SubmitRequestSUBJECT_INFOADDRESSType Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TypeSpecified
        {
            get
            {
                return this.typeFieldSpecified;
            }
            set
            {
                this.typeFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ns.verticalscreen.com/")]
    public enum SubmitRequestSUBJECT_INFOADDRESSType
    {
        
        /// <remarks/>
        Primary,
        
        /// <remarks/>
        Previous,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ns.verticalscreen.com/")]
    public partial class SubmitRequestSUBJECT_INFOPHONE
    {
        
        private string phoneNumField;
        
        private SubmitRequestSUBJECT_INFOPHONEType typeField;
        
        private bool typeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string PhoneNum
        {
            get
            {
                return this.phoneNumField;
            }
            set
            {
                this.phoneNumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public SubmitRequestSUBJECT_INFOPHONEType Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TypeSpecified
        {
            get
            {
                return this.typeFieldSpecified;
            }
            set
            {
                this.typeFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ns.verticalscreen.com/")]
    public enum SubmitRequestSUBJECT_INFOPHONEType
    {
        
        /// <remarks/>
        Home,
        
        /// <remarks/>
        Work,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ns.verticalscreen.com/")]
    public partial class SubmitRequestSERVICES
    {
        
        private SubmitRequestSERVICESEDUCATION[] eDUCATIONField;
        
        private SubmitRequestSERVICESEMPLOYMENT[] eMPLOYMENTField;
        
        private SubmitRequestSERVICESMVR[] mVRField;
        
        private SubmitRequestSERVICESDESIGNATION[] dESIGNATIONField;
        
        private SubmitRequestSERVICESPROFLICENSE[] pROFLICENSEField;
        
        private SubmitRequestSERVICESREFERENCE[] rEFERENCEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("EDUCATION", Order=0)]
        public SubmitRequestSERVICESEDUCATION[] EDUCATION
        {
            get
            {
                return this.eDUCATIONField;
            }
            set
            {
                this.eDUCATIONField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("EMPLOYMENT", Order=1)]
        public SubmitRequestSERVICESEMPLOYMENT[] EMPLOYMENT
        {
            get
            {
                return this.eMPLOYMENTField;
            }
            set
            {
                this.eMPLOYMENTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("MVR", Order=2)]
        public SubmitRequestSERVICESMVR[] MVR
        {
            get
            {
                return this.mVRField;
            }
            set
            {
                this.mVRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DESIGNATION", Order=3)]
        public SubmitRequestSERVICESDESIGNATION[] DESIGNATION
        {
            get
            {
                return this.dESIGNATIONField;
            }
            set
            {
                this.dESIGNATIONField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PROFLICENSE", Order=4)]
        public SubmitRequestSERVICESPROFLICENSE[] PROFLICENSE
        {
            get
            {
                return this.pROFLICENSEField;
            }
            set
            {
                this.pROFLICENSEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("REFERENCE", Order=5)]
        public SubmitRequestSERVICESREFERENCE[] REFERENCE
        {
            get
            {
                return this.rEFERENCEField;
            }
            set
            {
                this.rEFERENCEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ns.verticalscreen.com/")]
    public partial class SubmitRequestSERVICESEDUCATION
    {
        
        private string schoolNmField;
        
        private string schoolCityNmField;
        
        private string schoolStateCdField;
        
        private string schoolCountryCdField;
        
        private string schoolPhoneNumField;
        
        private string degreeNmField;
        
        private string majorNmField;
        
        private string attendedFromDtField;
        
        private string attendedToDtField;
        
        private string toPresentIndField;
        
        private string graduatedIndField;
        
        private string commentsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string SchoolNm
        {
            get
            {
                return this.schoolNmField;
            }
            set
            {
                this.schoolNmField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string SchoolCityNm
        {
            get
            {
                return this.schoolCityNmField;
            }
            set
            {
                this.schoolCityNmField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string SchoolStateCd
        {
            get
            {
                return this.schoolStateCdField;
            }
            set
            {
                this.schoolStateCdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string SchoolCountryCd
        {
            get
            {
                return this.schoolCountryCdField;
            }
            set
            {
                this.schoolCountryCdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string SchoolPhoneNum
        {
            get
            {
                return this.schoolPhoneNumField;
            }
            set
            {
                this.schoolPhoneNumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string DegreeNm
        {
            get
            {
                return this.degreeNmField;
            }
            set
            {
                this.degreeNmField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string MajorNm
        {
            get
            {
                return this.majorNmField;
            }
            set
            {
                this.majorNmField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string AttendedFromDt
        {
            get
            {
                return this.attendedFromDtField;
            }
            set
            {
                this.attendedFromDtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string AttendedToDt
        {
            get
            {
                return this.attendedToDtField;
            }
            set
            {
                this.attendedToDtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string ToPresentInd
        {
            get
            {
                return this.toPresentIndField;
            }
            set
            {
                this.toPresentIndField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string GraduatedInd
        {
            get
            {
                return this.graduatedIndField;
            }
            set
            {
                this.graduatedIndField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string Comments
        {
            get
            {
                return this.commentsField;
            }
            set
            {
                this.commentsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ns.verticalscreen.com/")]
    public partial class SubmitRequestSERVICESEMPLOYMENT
    {
        
        private string employerNmField;
        
        private string jobTitleField;
        
        private string fromEmployedDtField;
        
        private string toEmployedDtField;
        
        private string currentEmployerIndField;
        
        private string reasonForLeavingField;
        
        private string salaryLevelField;
        
        private string contactFirstNmField;
        
        private string contactLastNmField;
        
        private string contactJobTitleField;
        
        private string contactPhoneNumField;
        
        private string contactEmployerIndField;
        
        private string commentsField;
        
        private SubmitRequestSERVICESEMPLOYMENTADDRESS[] aDDRESSField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string EmployerNm
        {
            get
            {
                return this.employerNmField;
            }
            set
            {
                this.employerNmField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string JobTitle
        {
            get
            {
                return this.jobTitleField;
            }
            set
            {
                this.jobTitleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string FromEmployedDt
        {
            get
            {
                return this.fromEmployedDtField;
            }
            set
            {
                this.fromEmployedDtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ToEmployedDt
        {
            get
            {
                return this.toEmployedDtField;
            }
            set
            {
                this.toEmployedDtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string CurrentEmployerInd
        {
            get
            {
                return this.currentEmployerIndField;
            }
            set
            {
                this.currentEmployerIndField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string ReasonForLeaving
        {
            get
            {
                return this.reasonForLeavingField;
            }
            set
            {
                this.reasonForLeavingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string SalaryLevel
        {
            get
            {
                return this.salaryLevelField;
            }
            set
            {
                this.salaryLevelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string ContactFirstNm
        {
            get
            {
                return this.contactFirstNmField;
            }
            set
            {
                this.contactFirstNmField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string ContactLastNm
        {
            get
            {
                return this.contactLastNmField;
            }
            set
            {
                this.contactLastNmField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string ContactJobTitle
        {
            get
            {
                return this.contactJobTitleField;
            }
            set
            {
                this.contactJobTitleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string ContactPhoneNum
        {
            get
            {
                return this.contactPhoneNumField;
            }
            set
            {
                this.contactPhoneNumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string ContactEmployerInd
        {
            get
            {
                return this.contactEmployerIndField;
            }
            set
            {
                this.contactEmployerIndField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string Comments
        {
            get
            {
                return this.commentsField;
            }
            set
            {
                this.commentsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ADDRESS", Order=13)]
        public SubmitRequestSERVICESEMPLOYMENTADDRESS[] ADDRESS
        {
            get
            {
                return this.aDDRESSField;
            }
            set
            {
                this.aDDRESSField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ns.verticalscreen.com/")]
    public partial class SubmitRequestSERVICESEMPLOYMENTADDRESS
    {
        
        private string address1Field;
        
        private string address2Field;
        
        private string cityNmField;
        
        private string stateCdField;
        
        private string zipCodeField;
        
        private string countryCdField;
        
        private string typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Address1
        {
            get
            {
                return this.address1Field;
            }
            set
            {
                this.address1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Address2
        {
            get
            {
                return this.address2Field;
            }
            set
            {
                this.address2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string CityNm
        {
            get
            {
                return this.cityNmField;
            }
            set
            {
                this.cityNmField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string StateCd
        {
            get
            {
                return this.stateCdField;
            }
            set
            {
                this.stateCdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ZipCode
        {
            get
            {
                return this.zipCodeField;
            }
            set
            {
                this.zipCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string CountryCd
        {
            get
            {
                return this.countryCdField;
            }
            set
            {
                this.countryCdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ns.verticalscreen.com/")]
    public partial class SubmitRequestSERVICESMVR
    {
        
        private string stateCdField;
        
        private string licenseNmField;
        
        private string commentsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string StateCd
        {
            get
            {
                return this.stateCdField;
            }
            set
            {
                this.stateCdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string LicenseNm
        {
            get
            {
                return this.licenseNmField;
            }
            set
            {
                this.licenseNmField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Comments
        {
            get
            {
                return this.commentsField;
            }
            set
            {
                this.commentsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ns.verticalscreen.com/")]
    public partial class SubmitRequestSERVICESDESIGNATION
    {
        
        private string designationNmField;
        
        private string issuingOrgField;
        
        private string licenseIdField;
        
        private string yearsAssociatedField;
        
        private string commentsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string DesignationNm
        {
            get
            {
                return this.designationNmField;
            }
            set
            {
                this.designationNmField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string IssuingOrg
        {
            get
            {
                return this.issuingOrgField;
            }
            set
            {
                this.issuingOrgField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string LicenseId
        {
            get
            {
                return this.licenseIdField;
            }
            set
            {
                this.licenseIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string YearsAssociated
        {
            get
            {
                return this.yearsAssociatedField;
            }
            set
            {
                this.yearsAssociatedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Comments
        {
            get
            {
                return this.commentsField;
            }
            set
            {
                this.commentsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ns.verticalscreen.com/")]
    public partial class SubmitRequestSERVICESPROFLICENSE
    {
        
        private string licenseNmField;
        
        private string issuingOrgField;
        
        private string licenseIdField;
        
        private string effectiveDtField;
        
        private string expirationDtField;
        
        private string commentsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string LicenseNm
        {
            get
            {
                return this.licenseNmField;
            }
            set
            {
                this.licenseNmField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string IssuingOrg
        {
            get
            {
                return this.issuingOrgField;
            }
            set
            {
                this.issuingOrgField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string LicenseId
        {
            get
            {
                return this.licenseIdField;
            }
            set
            {
                this.licenseIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string EffectiveDt
        {
            get
            {
                return this.effectiveDtField;
            }
            set
            {
                this.effectiveDtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ExpirationDt
        {
            get
            {
                return this.expirationDtField;
            }
            set
            {
                this.expirationDtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Comments
        {
            get
            {
                return this.commentsField;
            }
            set
            {
                this.commentsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ns.verticalscreen.com/")]
    public partial class SubmitRequestSERVICESREFERENCE
    {
        
        private SubmitRequestSERVICESREFERENCENAME[] nAMEField;
        
        private SubmitRequestSERVICESREFERENCEADDRESS[] aDDRESSField;
        
        private SubmitRequestSERVICESREFERENCEPHONE[] pHONEField;
        
        private string emailAddressField;
        
        private string companyField;
        
        private string commentsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NAME", Order=0)]
        public SubmitRequestSERVICESREFERENCENAME[] NAME
        {
            get
            {
                return this.nAMEField;
            }
            set
            {
                this.nAMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ADDRESS", Order=1)]
        public SubmitRequestSERVICESREFERENCEADDRESS[] ADDRESS
        {
            get
            {
                return this.aDDRESSField;
            }
            set
            {
                this.aDDRESSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PHONE", Order=2)]
        public SubmitRequestSERVICESREFERENCEPHONE[] PHONE
        {
            get
            {
                return this.pHONEField;
            }
            set
            {
                this.pHONEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string EmailAddress
        {
            get
            {
                return this.emailAddressField;
            }
            set
            {
                this.emailAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Company
        {
            get
            {
                return this.companyField;
            }
            set
            {
                this.companyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Comments
        {
            get
            {
                return this.commentsField;
            }
            set
            {
                this.commentsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ns.verticalscreen.com/")]
    public partial class SubmitRequestSERVICESREFERENCENAME
    {
        
        private string firstNmField;
        
        private string middleNmField;
        
        private string lastNmField;
        
        private string typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string FirstNm
        {
            get
            {
                return this.firstNmField;
            }
            set
            {
                this.firstNmField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string MiddleNm
        {
            get
            {
                return this.middleNmField;
            }
            set
            {
                this.middleNmField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string LastNm
        {
            get
            {
                return this.lastNmField;
            }
            set
            {
                this.lastNmField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ns.verticalscreen.com/")]
    public partial class SubmitRequestSERVICESREFERENCEADDRESS
    {
        
        private string address1Field;
        
        private string address2Field;
        
        private string cityNmField;
        
        private string stateCdField;
        
        private string zipCodeField;
        
        private string countryCdField;
        
        private string typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Address1
        {
            get
            {
                return this.address1Field;
            }
            set
            {
                this.address1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Address2
        {
            get
            {
                return this.address2Field;
            }
            set
            {
                this.address2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string CityNm
        {
            get
            {
                return this.cityNmField;
            }
            set
            {
                this.cityNmField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string StateCd
        {
            get
            {
                return this.stateCdField;
            }
            set
            {
                this.stateCdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ZipCode
        {
            get
            {
                return this.zipCodeField;
            }
            set
            {
                this.zipCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string CountryCd
        {
            get
            {
                return this.countryCdField;
            }
            set
            {
                this.countryCdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ns.verticalscreen.com/")]
    public partial class SubmitRequestSERVICESREFERENCEPHONE
    {
        
        private string phoneNumField;
        
        private string typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string PhoneNum
        {
            get
            {
                return this.phoneNumField;
            }
            set
            {
                this.phoneNumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ns.verticalscreen.com/")]
    public partial class SubmitRequestCUSTOMTYPE
    {
        
        private string valueField;
        
        private string commentsField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Comments
        {
            get
            {
                return this.commentsField;
            }
            set
            {
                this.commentsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ns.verticalscreen.com/")]
    public partial class SubmitResponseSubmitResult
    {
        
        private string userNmField;
        
        private string userPwdField;
        
        private string requestIdField;
        
        private string requestReceivedDtField;
        
        private string statusCdField;
        
        private string descriptionField;
        
        private string uriLinkField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string UserNm
        {
            get
            {
                return this.userNmField;
            }
            set
            {
                this.userNmField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string UserPwd
        {
            get
            {
                return this.userPwdField;
            }
            set
            {
                this.userPwdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string RequestId
        {
            get
            {
                return this.requestIdField;
            }
            set
            {
                this.requestIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string RequestReceivedDt
        {
            get
            {
                return this.requestReceivedDtField;
            }
            set
            {
                this.requestReceivedDtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string StatusCd
        {
            get
            {
                return this.statusCdField;
            }
            set
            {
                this.statusCdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string UriLink
        {
            get
            {
                return this.uriLinkField;
            }
            set
            {
                this.uriLinkField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface TokioMarineWebServiceSoapV2Channel : BIGWebServiceReference.TokioMarineWebServiceSoapV2, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class TokioMarineWebServiceSoapV2Client : System.ServiceModel.ClientBase<BIGWebServiceReference.TokioMarineWebServiceSoapV2>, BIGWebServiceReference.TokioMarineWebServiceSoapV2
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public TokioMarineWebServiceSoapV2Client() : 
                base(TokioMarineWebServiceSoapV2Client.GetDefaultBinding(), TokioMarineWebServiceSoapV2Client.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.TokioMarineWebServiceSoapV2.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TokioMarineWebServiceSoapV2Client(EndpointConfiguration endpointConfiguration) : 
                base(TokioMarineWebServiceSoapV2Client.GetBindingForEndpoint(endpointConfiguration), TokioMarineWebServiceSoapV2Client.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TokioMarineWebServiceSoapV2Client(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(TokioMarineWebServiceSoapV2Client.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        /// <summary>
        /// Manually add a new constructor to take ClientCredentials parameter
        /// </summary>
        /// <param name="endpointConfiguration"></param>
        /// <param name="remoteAddress"></param>
        /// <param name="clientCredentials"></param>
        public TokioMarineWebServiceSoapV2Client(EndpointConfiguration endpointConfiguration, string remoteAddress, System.ServiceModel.Description.ClientCredentials clientCredentials) :
                base(TokioMarineWebServiceSoapV2Client.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, clientCredentials);
        }

        public TokioMarineWebServiceSoapV2Client(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(TokioMarineWebServiceSoapV2Client.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TokioMarineWebServiceSoapV2Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<BIGWebServiceReference.SubmitResponseSubmitResult> SubmitAsync(BIGWebServiceReference.SubmitRequest Request)
        {
            return base.Channel.SubmitAsync(Request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.TokioMarineWebServiceSoapV2))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.TokioMarineWebServiceSoapV2))
            {
                return new System.ServiceModel.EndpointAddress("https://accintegrations.verticalscreen.com/V2/TokioMarine");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return TokioMarineWebServiceSoapV2Client.GetBindingForEndpoint(EndpointConfiguration.TokioMarineWebServiceSoapV2);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return TokioMarineWebServiceSoapV2Client.GetEndpointAddress(EndpointConfiguration.TokioMarineWebServiceSoapV2);
        }
        
        public enum EndpointConfiguration
        {
            
            TokioMarineWebServiceSoapV2,
        }
    }
}
